# Generated by Django 6.0.4 on 2026-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='38100', max_length=20),
            preserve_default=False,
        ),
    ]
